from fractal.loaders.aave import AaveV2EthereumLoader, AaveV3ArbitrumLoader, AaveV3EthereumLoader, AaveV3RatesLoader
from fractal.loaders.base_loader import Loader, LoaderType
from fractal.loaders.binance import (
    BinanceDayPriceLoader,
    BinanceFundingLoader,
    BinanceHourPriceLoader,
    BinanceKlinesLoader,
    BinancePriceLoader,
    BinanceSpotPriceLoader,
)
from fractal.loaders.boros import BorosMarketInfo, BorosMarketLoader
from fractal.loaders.defillama import (
    DefiLlamaDEXLoader,
    DefiLlamaPoolLoader,
    DefiLlamaProLoader,
    DefiLlamaTVLLoader,
    DefiLlamaYieldsLoader,
)
from fractal.loaders.gmx_v1 import GMXV1FundingLoader
from fractal.loaders.hyperliquid import (  # Pre-1.3.0 alias.
    HyperliquidFundingRatesLoader,
    HyperliquidPerpsKlinesLoader,
    HyperLiquidPerpsPricesLoader,
    HyperliquidPerpsPricesLoader,
)
from fractal.loaders.morpho import MorphoMarketInfo, MorphoMarketLoader
from fractal.loaders.onchain import RpcLoaderException, UniswapV3SwapsLoader
from fractal.loaders.pendle import PendleMarketInfo, PendleMarketLoader, PendleMarketState, PendleOHLCVLoader
from fractal.loaders.rpc import JsonRpcClient, RpcCallError
from fractal.loaders.simulations import ConstantFundingsLoader, MonteCarloHourPriceLoader, MonteCarloPriceLoader
from fractal.loaders.structs import (
    BorosMarketHistory,
    DEXHistory,
    FundingHistory,
    KlinesHistory,
    LendingHistory,
    PendleMarketHistory,
    PoolHistory,
    PriceHistory,
    RateHistory,
    SwapsHistory,
    TrajectoryBundle,
    TVLHistory,
)
from fractal.loaders.thegraph import (
    AerodromeLoader,
    AerodromeSlipstreamPoolHourDataLoader,
    ArbitrumGraphLoader,
    BaseGraphLoader,
    BaseUniswapV3Loader,
    EthereumUniswapV2PoolDataLoader,
    GraphLoaderException,
    StETHLoader,
    UniswapV3ArbitrumPoolDayDataLoader,
    UniswapV3ArbitrumPoolHourDataLoader,
    UniswapV3ArbitrumPricesLoader,
    UniswapV3BasePoolHourDataLoader,
    UniswapV3EthereumPoolDayDataLoader,
    UniswapV3EthereumPoolHourDataLoader,
    UniswapV3EthereumPoolMinuteDataLoader,
    UniswapV3EthereumPricesLoader,
)

__all__ = [
    "AaveV2EthereumLoader",
    "AaveV3ArbitrumLoader",
    "AaveV3EthereumLoader",
    "AaveV3RatesLoader",
    "AerodromeLoader",
    "AerodromeSlipstreamPoolHourDataLoader",
    "ArbitrumGraphLoader",
    "BaseGraphLoader",
    "BaseUniswapV3Loader",
    "BinanceDayPriceLoader",
    "BinanceFundingLoader",
    "BinanceHourPriceLoader",
    "BinanceKlinesLoader",
    "BinancePriceLoader",
    "BinanceSpotPriceLoader",
    "BorosMarketHistory",
    "BorosMarketInfo",
    "BorosMarketLoader",
    "ConstantFundingsLoader",
    "DEXHistory",
    "DefiLlamaDEXLoader",
    "DefiLlamaPoolLoader",
    "DefiLlamaProLoader",
    "DefiLlamaTVLLoader",
    "DefiLlamaYieldsLoader",
    "EthereumUniswapV2PoolDataLoader",
    "FundingHistory",
    "GMXV1FundingLoader",
    "GraphLoaderException",
    # Pre-1.3.0 alias (deprecated; will be removed in a future major release).
    "HyperLiquidPerpsPricesLoader",
    "HyperliquidFundingRatesLoader",
    "HyperliquidPerpsKlinesLoader",
    "HyperliquidPerpsPricesLoader",
    "JsonRpcClient",
    "KlinesHistory",
    "LendingHistory",
    "Loader",
    "LoaderType",
    "MonteCarloHourPriceLoader",
    "MonteCarloPriceLoader",
    "MorphoMarketInfo",
    "MorphoMarketLoader",
    "PendleMarketHistory",
    "PendleMarketInfo",
    "PendleMarketLoader",
    "PendleMarketState",
    "PendleOHLCVLoader",
    "PoolHistory",
    "PriceHistory",
    "RateHistory",
    "RpcCallError",
    "RpcLoaderException",
    "StETHLoader",
    "SwapsHistory",
    "TVLHistory",
    "TrajectoryBundle",
    "UniswapV3ArbitrumPoolDayDataLoader",
    "UniswapV3ArbitrumPoolHourDataLoader",
    "UniswapV3ArbitrumPricesLoader",
    "UniswapV3BasePoolHourDataLoader",
    "UniswapV3EthereumPoolDayDataLoader",
    "UniswapV3EthereumPoolHourDataLoader",
    "UniswapV3EthereumPoolMinuteDataLoader",
    "UniswapV3EthereumPricesLoader",
    "UniswapV3SwapsLoader",
]
